version: "3"
services: 
    front-end:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        restart: "always"
        volumes:
            - .:/app
            - /app/node_modules
        stdin_open: true
    front-end-test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - /app/node_modules
        command: ["yarn", "run", "test"]